name: "My personal frida-gadget with small size (arm)"

on:
  workflow_dispatch:
    inputs:
      from:
        description: "Enter branch/tag to build frida from(Default : main)"
        required: false
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "10"

      - name: Setup JDK 1.8
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Setup Python 3.10
        uses: actions/setup-python@v3.1.2
        with:
          python-version: "3.10"

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1.0.6
        with:
          ndk-version: r24-beta1

      - name: Install dependencies
        run: |
          sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install build-essential tree ninja-build gcc-multilib g++-multilib lib32stdc++-9-dev flex bison xz-utils ruby ruby-dev python3-requests python3-setuptools python3-dev python3-pip libc6-dev libc6-dev-i386 -y
          sudo gem install fpm -v 1.11.0 --no-document
          python3 -m pip install lief

      - name: Build frida for Android
        shell: bash
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git clone -b ${{ github.event.inputs.from }} --recurse-submodules https://github.com/frida/frida
          git clone https://github.com/kyzsukii/frida-gadget-thin
          cd frida/frida-core
          git am ../../frida-gadget-thin/patches/frida/frida-core/*.patch
          cd ../
          git apply ../frida-gadget-thin/patches/frida/thin/config_mk.patch
          make core-android-arm

      - name: Package build result for Android
        shell: bash
        run: |
          pushd frida
          
          xz build/frida-android-arm/lib/frida/32/frida-gadget.so

          popd

      - name: Upload frida-gadget-arm
        uses: actions/upload-artifact@v3
        with:
          name: frida-gadget-arm.xz
          path: frida/build/frida-android-arm/lib/frida/32/frida-gadget.so.xz